### 
GET http://localhost:3000/api/produtos
Accept: application/json

###
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
  "nome": "Caixa de Papelão P",
  "categoria": "Embalagens",
  "preco": 2.50,
  "estoque_minimo": 10
}

###

PUT http://localhost:3000/api/produtos/4
Content-Type: application/json

{
  "nome": "Caixa de Papelão M",
  "categoria": "Embalagens",
  "quantidade": 150,
  "preco": 12.00,
  "estoque_minimo": 15
}

### 
GET http://localhost:3000/api/produtos/4
Accept: application/json

### 
DELETE http://localhost:3000/api/produtos/4

### 
GET http://localhost:3000/api/produtos 
Accept: application/json

### 
POST http://localhost:3000/api/produtos 
Content-Type: application/json

{
  "nome": "Caixa de Papelão P",
  "categoria": "Embalagens",
  "preco": 2.50,
  "estoque_minimo": 10
} 

### 
PUT http://localhost:3000/api/produtos/4 
Content-Type: application/json

{
  "nome": "Caixa de Papelão M",
  "categoria": "Embalagens",
  "quantidade": 150,
  "preco": 12.00,
  "estoque_minimo": 15
} 

### 
GET http://localhost:3000/api/produtos/4 
Accept: application/json

### 
DELETE http://localhost:3000/api/produtos/4 


### 
POST http://localhost:3000/api/movimentacoes
Content-Type: application/json

{
  "produto_id": 1,
  "tipo": "entrada",
  "quantidade": 50
}

### 
POST http://localhost:3000/api/movimentacoes
Content-Type: application/json

{
  "produto_id": 1,
  "tipo": "saida",
  "quantidade": 45
}

### 
GET http://localhost:3000/api/movimentacoes
Accept: application/json

### 
GET http://localhost:3000/api/produtos/alertas
Accept: application/json

### 
GET http://localhost:3000/api/produtos/relatorio
Accept: application/json